### ISSUE TITLE
Erro with test on MSMARCO dataset.

### ISSUE THREAD

**Issue by zyznull** [HKUNLP/instructor-embedding#1]
I have try to do the evaluation following read me. When I run:
`
python examples/evaluate_model.py --model_name hkunlp/instructor-large --output_dir msmarco.out --task_name MSMARCO  --result_file msmarco.res
`
I met the following erro:
`
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
`

**Comment by Harry-hash** [comment]
Hi, thanks for your interest!

Following the MTEB leaderbaord, the MSMARCO dataset is evaluated on the dev split, and this is done by simply appending `--split dev` at the end. Note that the results may be different from paper as we have trained a new checkpoint with hard negatives.

For the error you described, if the score shows in `result_file` or can be printed out, you may ignore the error. Otherwise, you may check your `beir` version. The code is now working with version 1.0.0.

Hope this helps!

**Comment by Harry-hash** [comment]
Feel free to reopen the issue if there is any part unclear!
