### ISSUE TITLE
Other model bases?

### ISSUE THREAD

**Issue by robbohua** [HKUNLP/instructor-embedding#15]
Thanks for this repo! I noticed that Instructor is initialised from a T5 / GTR

In your experiments how crucial is this base - if we were to try train say a MPNET or BERT with this dataset has this been explored?

Just wondering before I bite the bullet on this!

**Comment by Harry-hash** [comment]
Hi, thanks a lot for your interests in INSTRUCTOR!

We have not tried initializing INSTRUCTOR from MPNET or BERT because they are not ranked the highest in [MTEB leaderboard](https://huggingface.co/spaces/mteb/leaderboard) (all-mpnet-base-v2 ranks 13). However, it would be very interesting if we can demonstrate BERT-like models also have instruction-following capabilities in calculating sentence embeddings.

Hope this helps! Feel free to leave any further question or comment here!

**Comment by Harry-hash** [comment]
Feel free to re-open the issue if you have further questions or comments!
